spring:
  application:
    name: message-service

---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: message-service-local

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: message-service-dev

---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: message-service-prod

app:
  security:
    public-endpoints:
      - /actuator/health
    user-endpoints:
      - /api/v1/**
    integration-endpoints:
      - /integration/v1/**
