CREATE TABLE app_user (
  id BINARY(16) PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(512) NULL,
  status VARCHAR(32) NOT NULL,
  version BIGINT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT uk_app_user_username UNIQUE (username)
);
